#ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-editor-cr
  labels:
    app: policy-editor
    app.kubernetes.io/name: policy-editor
rules:
  - apiGroups: [ "" ]
    resources:
      - namespaces
    verbs: [ "get", "list" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - networkpolicies
    verbs: [ "*" ]
  - nonResourceURLs: [ "*" ]
    verbs: [ "get", "list" ]
---
#ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-editor-sa
  namespace: default
  labels:
    app: policy-editor
    app.kubernetes.io/name: policy-editor
---
#ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-editor-crb
  namespace: default
roleRef:
  kind: ClusterRole
  name: policy-editor-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: policy-editor-sa
    namespace: default
